import React from "react";
import { Inter } from "next/font/google";
import { Metadata } from "next";
import { AssetProvider } from '../context/AssetContext';

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "EA Test App",
  description: "Generated by create next app",
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html lang="en">
      <AssetProvider>
        <body className={inter.className}>{children}</body>
      </AssetProvider>

    </html>
  );
};

export default RootLayout;